[book]
authors = ["Cody Luo"]
language = "zh_CN"
multilingual = false
src = "src"
title = "数学演示"

[output.html]
git-repository-url = "https://github.com/mathdemos/mathdemos.github.io"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/mathdemos/mathdemos.github.io/edit/main/{path}"
additional-js = ["sagecell.js"]
additional-css = ["sagecell_embed.css"]
no-section-label = false
curly-quotes = false

[preprocessor.katex]
after = ["links"]
block-delimiter = { left = "$$", right = "$$" }
inline-delimiter = { left = "$", right = "$" }
#pre-render = true

[output.html.playground]
editable = true
